/** Positional field orders for the semicolon-delimited EV3 format. */

/** Event-record field names, in file order (30 fields). */
export const EVENT_FIELD_NAMES = [
  'event_no',
  'subevent_no',
  'prelims_finals',
  'rounds',
  'ind_or_relay',
  'gender',
  'min_age',
  'max_age',
  'distance',
  'stroke',
  'number_of_dives',
  'division_code',
  'division_name',
  'event_type',
  'event_fee',
  'lcm_dqt',
  'lcm_qt',
  'scm_dqt',
  'scm_qt',
  'scy_dqt',
  'scy_qt',
  'session_number',
  'session_event',
  'session_meet_day',
  'session_start_time',
  'session_course',
  'max_entries',
  'max_individual_entries',
  'max_relay_entries',
  'relay_team_members',
] as const;

/** Header-record field names, in file order (35 fields; last is the check digit). */
export const HEADER_FIELD_NAMES = [
  'meet_name',
  'pool_name',
  'meet_start_date',
  'meet_end_date',
  'age_up_date',
  'seeding_type',
  'team_surcharge',
  'athlete_surcharge',
  'facility_surcharge',
  'file_format',
  'meet_software',
  'meet_sw_version',
  'date_generated',
  'unknown1',
  'sanction_number',
  'altitude',
  'valid_times_start_date',
  'minimum_age_open_events',
  'max_total_entries',
  'max_individual_entries',
  'max_relay_entries',
  'id_format',
  'class',
  'entry_deadline',
  'pool_address1',
  'pool_address2',
  'pool_city',
  'pool_province',
  'pool_postal_code',
  'pool_country',
  'host_LSC',
  'exclude_notimes',
  'use_min_conforming_course_time_if_qt_non_conforming',
  'entry_open_date',
  'check_digit',
] as const;
